# Generated by Django 5.1.4 on 2024-12-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='business_type',
        ),
    ]
