# Generated by Django 5.1.4 on 2024-12-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('clothing', 'Clothing')], max_length=500, null=True),
        ),
    ]
